### PR TITLE
Add easy-to-run demo of Mandelbrot in BDV

### PR DESCRIPTION
**Pull request by ctrueden**
I couldn't find this code in a runnable-out-of-the-box form, so I created a main method which runs it.

Thanks to @axtimwalde for the pointer; see [this discussion on Gitter](https://gitter.im/imglib/imglib2?at=5a0216d786d308b755bd4470).

### CODE REVIEW

**Comment by axtimwalde** [comment]
May be we should include `MandelbrotRealRandomAccessible` and `JuliaRealARandomAccessible` in `imglib2` core and make this an example in bdv-vistools?

**Comment by ctrueden** [comment]
Sorry @axtimwalde... where is the existing example? That's what I meant by "I couldn't find this code in a runnable-out-of-the-box form." If it's already somewhere else, then by all means, let's close this PR without merging.

**Comment by axtimwalde** [comment]
The existing example in this very project that uses the interactive viewer that eventually evolved into BDV

https://github.com/imglib/imglib2-tutorials/blob/master/src/main/java/interactive/MandelbrotRealViewer2DExample.java

But I like the idea to have a 'modern' version of this using `BdvFunctions` somewhere.

**Comment by ctrueden** [comment]
> But I like the idea to have a 'modern' version of this using BdvFunctions somewhere.

The BDV dependencies are only test scope here, so maybe that's OK? And anyway, no one depends on the imglib2-tutorials artifact for anything, right? We've never cut a release... so who cares what dependencies it has?

**Comment by ctrueden** [comment]
I'm gonna be gauche and just merge my own PR here, since it seems like people don't have strong objections. If someone hates it, we can revert.

**Pull request merged**
